---
- name: install dependencies
  shell: "cd {{ build_path }} && gpm install"

- name: build binary
  shell: "cd {{ build_path }} && go build -o revisioneer"

- name: migrate database
  shell: "cd {{ build_path }} && sqitch deploy"
  register: sqitch_result
  failed_when: "'FATAL' in sqitch_result.stderr"