---
- name: install dependencies
  shell: "cd {{ build_path }} && gpm install"
  environment:
    GOPATH: "{{ home_directory }}/go"

- name: build binary
  shell: "cd {{ build_path }} && go build -o revisioneer"
  environment:
    GOPATH: "{{ home_directory }}/go"
