---
- hosts: revisioneer
  sudo: true
  tags: provision
  roles:
    -
      role: database
    -
      role: webserver
    -
      role: revisioneer
    -
      role: nicolai86.godeb

- hosts: revisioneer
  remote_user: "{{ user }}"
  tags: deploy
  vars:
    home_directory: "/home/{{ user }}"

    deploy_to: "{{ home_directory }}"
    # build_path: "{{ deployment.build_path }}"
    # release_path: "{{ deploy_to }}/releases/{{ deployment.timestamp }}"
    # shared_path: "{{ deploy_to }}/shared"
    # current_path: "{{ deploy_to }}/current"

    directories:
      - "{{ deploy_to }}/releases"
      - "{{ shared_path }}/log"
      - "{{ shared_path }}/tmp"

  roles:
    -
      role: nicolai86.prepare-release

      repo: "git@github.com:nicolai86/revisioneer.git"
      branch: "master"

    -
      role: deploy

    -
      role: nicolai86.finalize-release

    -
      role: restart

    -
      role: nicolai86.ansible-revisioneer

      repository_path: "{{ deploy_to }}/scm"
      revisioneer_token: "{{ revisioneer_api_token }}"