---
# postgresql management
- name: create revisioneer database
  sudo_user: postgres
  postgresql_db:
    name: "{{ database }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'

- name: create revisioneer db user
  sudo_user: postgres
  postgresql_user:
    db: "{{ database }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    priv: ALL

# user management
- name: create revisioneer user
  user:
    name: "{{ user }}"
    home: "{{ home_directory }}"
    createhome: yes
    shell: "/bin/bash"
    state: present

# ssh authorized key
- authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    manage_dir: no

- file:
    path: "{{ home_directory }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

# supervisor
- apt: pkg={{ item }} state=installed
  with_items:
    - supervisor

- template:
    src: supervisor/revisions.js
    dest: /etc/supervisor/conf.d/revisions.conf
    owner: root
    group: root
    mode: 0600

- service:
    name: supervisor
    state: started

- shell: "supervisorctl reread && supervisorctl update"

- name: allow sudo access to supervisorctl
  lineinfile:
    dest: "/etc/sudoers"
    insertafter: EOF
    regexp: "^{{ user }}"
    line: "{{ user }} ALL=NOPASSWD: /usr/bin/supervisorctl"
    state: present

- name: ensure proper sudo permissions
  shell: "chmod 4755 $(which sudo)"

# install gpm
- git:
    repo: https://github.com/pote/gpm.git
    dest: /tmp/gpm
    version: v1.0.1
  tags: test

- shell: chdir=/tmp/gpm ./configure && make install
  tags: test