---
- name: install postgresql
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - postgresql
    - postgresql-common
    - postgresql-client
    - postgresql-client-common

- name: start postgresql
  service:
    name: postgresql
    state: started