---
- name: update apt cache
  apt: update-cache=yes

- name: install common dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - python
    - python-psycopg2
    - python-software-properties
    - build-essential
    - make
    - htop
    - git-core
    - cmake