---
- apt: pkg={{ item }} state=installed
  with_items:
    - nginx

- template:
    src: nginx/revisioneer.js
    dest: /etc/nginx/sites-available/revisioneer
    owner: root
    group: root
    mode: 0600

- file:
    src: /etc/nginx/sites-available/revisioneer
    path: /etc/nginx/sites-enabled/revisioneer
    state: link

- file:
    path: "{{ ssl_path }}"
    owner: root
    group: root
    mode: 0600
    state: directory
    recurse: yes

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "{{ ssl_path }}"
    owner: root
    group: root
    mode: 0600
  with_fileglob: ssl/*
  when: use_ssl